version: '3.9'
services:
  app:
    depends_on:
      - mysqldb
    build:
      context: .
    container_name: blog_api
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://$MYSQLDB_HOST:$MYSQLDB_LOCAL_PORT/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_USERNAME: $MYSQLDB_USER
        SPRING_DATASOURCE_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    platform: linux/amd64
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_ROOT_HOST=$MYSQL_ROOT_HOST
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_LOCAL_PORT
    volumes:
      - mydata:/var/lib/mysql
    networks:
      - backend

volumes:
  mydata: {}

networks:
  backend: